# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nSeqs <- function(files) {
    .Call('FindMyFriends_nSeqs', PACKAGE = 'FindMyFriends', files)
}

readFasta <- function(files, indexes) {
    .Call('FindMyFriends_readFasta', PACKAGE = 'FindMyFriends', files, indexes)
}

test <- function() {
    .Call('FindMyFriends_test', PACKAGE = 'FindMyFriends')
}

panSim <- function(pg) {
    .Call('FindMyFriends_panSim', PACKAGE = 'FindMyFriends', pg)
}

