# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nSeqs <- function(files) {
    .Call('FindMyFriends_nSeqs', PACKAGE = 'FindMyFriends', files)
}

linearKernel <- function(pX, jX, xX, selX, lowerLimit, upperLimit) {
    .Call('FindMyFriends_linearKernel', PACKAGE = 'FindMyFriends', pX, jX, xX, selX, lowerLimit, upperLimit)
}

getClusters <- function(nNodes, I, P, X) {
    .Call('FindMyFriends_getClusters', PACKAGE = 'FindMyFriends', nNodes, I, P, X)
}

panSim <- function(pg) {
    .Call('FindMyFriends_panSim', PACKAGE = 'FindMyFriends', pg)
}

